# config.
version: "3"

networks:
    frota-net:
        driver: bridge

# volumes.
volumes:
    frota-database-data:
    frota-redis-data:
    frota-dot-config:
    frota-dot-local:
    frota-dot-cache:
    frota-dot-composer:
    frota-auth-node_modules:
    frota-dashboard-node_modules:
    frota-settings-node_modules:

        # services.
services:
    # MySQL.
    db:
        container_name: frota-mysql
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        tty: true
        networks:
            - frota-net
        volumes:
            - frota-database-data:/var/lib/mysql
            - './.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
        ports:
            - 33307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=frotablit
            - MYSQL_DATABASE=frota
            - MYSQL_USER=frota
            - MYSQL_PASSWORD=frota
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    app:
        container_name: frota-app
        build: ./.docker/php
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
        networks:
            - frota-net
        depends_on:
            - db
            - redis
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    horizon:
        build: ./.docker/php
        container_name: frota-horizon
        command: php artisan horizon
        volumes:
            - .:/var/www
        depends_on:
            - redis
        networks:
            - frota-net
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    nginx:
        container_name: frota-nginx
        build: ./.docker/nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
        networks:
            - frota-net
        depends_on:
            - app
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    redis:
        container_name: frota-redis
        image: redis:6-alpine
        command: redis-server --bind 0.0.0.0 --requirepass '@secret99D'
        restart: unless-stopped
        networks:
            - frota-net
        volumes:
            - frota-redis-data:/data
        ports:
            - 6379
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    mailhog:
        container_name: frota-mailhog
        image: mailhog/mailhog
        environment:
            MAIL_MAILER: smtp
            MAIL_HOST: 127.0.0.1
            MAIL_PORT: 1025
        networks:
            - frota-net
        ports:
            - 1025:1025
            - 8025:8025
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
